name: cxxsim build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  cxxsim-build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SDL
      run: sudo apt install libsdl2-dev libsdl2-2.0-0 -y

    - name: Set up Chryse
      uses: chryse-hdl/setup-chryse-action@v1
      with:
        install-oss-cad-suite: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Elaborate and compile cxxsim
      run: sbt 'run cxxsim -c'
