name: Synthesis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  synthesis:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Chryse
      uses: chryse-hdl/setup-chryse-action@v2.1
      with:
        install-oss-cad-suite: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Elaborate and synthesise
      run: sbt 'run build'
